datasets:
  data_dir: 'data/synthetic'
  topics: 'therapy'
  therapy_source_dir: 'data/source/HOPE_WSDM_2022/conversations'
  legal_source_dir: 'data/source/legal'
  writing_source_dir: 'data/source/creative_writing/human_wp_stories_cleaned.json'
  email_source_dir: 'data/source/email_records/filtered_files_sager-e.txt'
  persona_file: 'data/source/Persona_Hub_200000.jsonl'
  random_questions_dir: 'data/random_questions'
  random_contexts_file: 'data/output/irrelevant_contexts.json'
models:
  llm_model: 'gpt-5-mini'  # default generation model
  api_mode: 'auto'  # auto | assistants | responses | chat
  api_base_url: ''
  api_key_file: 'openai_key.txt'
  gemini_credential_path: 'google-cloud-sdk/google_gemini_credential.json'
inference:
  verbose: False
  print_every: 50
  num_personas: 1
  num_samples_per_context: 1
  start_persona_idx: 0
  start_sample_idx: 0
  output_dir: 'data/output/'
  save_output_response: True
  output_file_name: 'conversation'
